#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 360
#define WINDOW_FRAMERATE 60
#define GAME_TILE_SIZE 12
#define PLAYER_WALK_SPEED 4
#define PLAYER_RUN_SPEED 8
#define PLAYER_JUMP_SPEED 10
#define PLAYER_GRAVITY 12